# ==========================
#  CONFIG ORACLE
# ==========================

# Si usas ORACLE XE con SID = XE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE

# Si tu usuario es el que creaste en SQL Developer:
spring.datasource.username=kart
spring.datasource.password=kart

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ==========================
#  JPA / HIBERNATE
# ==========================

# Opciones:
# validate → solo valida que las entidades coincidan con la BD
# update   → crea/ajusta tablas automáticamente (útil en desarrollo)
# none     → no toca el esquema
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace



# ==========================
#  ZONA HORARIA (opcional)
# ==========================
spring.jpa.properties.hibernate.jdbc.time_zone=America/Santiago


# ==========================
#  SERVER
# ==========================
server.port=8080




